version: '3.4'
services:

  rasa:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: './'
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./tests:/app/tests
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5006:5005'
    depends_on:
    - rasa-actions
    public: true
    env_file: .env
    networks:
    - all

  rasa-actions:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: './'
    restart: always
    volumes:
    - ./actions:/app/actions
    command: bash -c "rasa run actions"
    ports:
    - '5055:5055'
    env_file: .env
    networks:
    - all

  rabbit:
    restart: always
    image: "bitnami/rabbitmq:3.7.17"
    environment:
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_USERNAME: "user"
      RABBITMQ_PASSWORD: user123
      RABBITMQ_DISK_FREE_LIMIT: "{mem_relative, 0.1}"
    expose:
      - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
<<<<<<< HEAD
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
=======
    image: elasticsearch:8.0.1
>>>>>>> 88c9ff8ccb3fa83b07bb98942eeed5c3eba7f0cd
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    ulimits:
      memlock:
        soft: -1
        hard: -1


  kibana:
    image: kibana:8.0.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  

  logstash:
    image: logstash:8.0.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - '5000:5000'
    networks:
      - elk
    depends_on:
      - elasticsearch

  

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable.ipv6: "true"
  
  elk:
    driver:bridge
